version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
    volumes:
      - .:/app
      - ./rails-storage:/var/www/rails/storage
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: jruby_rails_test
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql